sudo: required

language: node_js

services:
  - docker

jobs:
  include:
    - stage: test      
      before_install:
        - ls -lR
      script: npm run setup

    - stage: build docker image
      install: docker build -t oferzi23/react-example .
      script: docker ps -a

    - stage: run docker image
      script: docker run -d -p 8080:8080 oferzi23/react-example 