sudo: required


services:
  - docker

language: node_js
node_js: 
  - "6"

before_install:
  - sudo apt install jq

env: 
  - BUILD_VERSION="$(cat package.json | jq -r '.version')-${TRAVIS_BUILD_NUMBER}"

jobs:
  include:
    - stage: test      
      before_install:
        - ls -lR
        - echo "Testing Version ${BUILD_VERSION}"
      script: npm run setup

    - stage: build docker image
      before_install:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      install: 
       - docker build -t "oferzi23/react-example:$BUILD_VERSION" .
       
      script: docker images -a
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
          docker push oferzi23/react-example;
          fi

    - stage: deploy
      script: echo "deployment"
     