sudo: required

language: node_js
node_js: 6

services:
  - docker

jobs:
  include:
    - stage: test      
      before_install:
        - ls -lR
      script: npm run setup

    - stage: build docker image
      before_install:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      install: 
       - docker build -t oferzi23/react-example .
       
      script: docker images -a
      after_success:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
          docker push oferzi23/react-example;
          fi

    - stage: deploy
      script: echo "deployment"
     