---
- hosts: localhost

  vars_prompt:
    - name: "owner"
      prompt: "Enter Owner"
      private: no

    - name: "repository"
      prompt: "Enter Repository Name"
      private: no

    - name: "tag"
      prompt: "Enter Tag"
      private: no
    
  tasks:

  - name: "react-example container"
    docker:
      name: test
      image: "{{owner}}/{{repository}}:tag"
      state: started
      ports: 
        - "8080:8080"